import unittest
from pathlib import Path

from omnidoer.omni_control.server import lite_static_root, static_root


class ControlUiContractTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.root = Path(__file__).resolve().parents[1]
        cls.html = (static_root() / "index.html").read_text()
        cls.app = (static_root() / "app.js").read_text()

    def test_secret_explanation_present(self) -> None:
        self.assertIn("Secret Broker", self.html)
        self.assertIn("Not sent to Agent/LLM context", self.html)
        self.assertIn("MCP return values", self.html)

    def test_lite_client_keeps_only_pairing_core_approvals_and_streaming_chat(self) -> None:
        lite_html = (lite_static_root() / "index.html").read_text()
        lite_app = (lite_static_root() / "lite.js").read_text()
        lite_style = (lite_static_root() / "lite.css").read_text()
        cli_main = (self.root / "omnidoer" / "omni_cli" / "main.py").read_text()
        client_cli = (self.root / "omnidoer" / "omni_control" / "client_cli.py").read_text()

        self.assertIn("OmniDoer Lite", lite_html)
        self.assertIn('rel="manifest"', lite_html)
        self.assertIn("apple-mobile-web-app-capable", lite_html)
        self.assertIn("apple-touch-icon", lite_html)
        self.assertIn("boot-screen", lite_html)
        self.assertIn("pair-code", lite_html)
        self.assertIn("chat-files", lite_html)
        self.assertIn("selected-files", lite_html)
        self.assertIn("核心审批", lite_html)
        self.assertIn("消息", lite_html)
        self.assertIn("/api/lite/state", lite_app)
        self.assertIn("/api/pair", lite_app)
        self.assertIn("/api/broker-key", lite_app)
        self.assertIn("encryptForBroker", lite_app)
        self.assertIn("CORE_SECRET_TYPES", lite_app)
        self.assertIn("HIGH_RISK_TYPES", lite_app)
        self.assertIn("/api/chat/events?stream=1", lite_app)
        self.assertIn("/api/chat/attachments", lite_app)
        self.assertIn("uploadChatAttachments", lite_app)
        self.assertIn("renderAttachmentList", lite_app)
        self.assertIn("streamChatOnce", lite_app)
        self.assertIn("liveTerminalMessage", lite_app)
        self.assertIn("interval=0.18", lite_app)
        self.assertIn("markReady", lite_app)
        self.assertIn(".boot-screen", lite_style)
        self.assertNotIn("takeover-panel", lite_html)
        self.assertNotIn("devices-list", lite_html)
        self.assertNotIn("security-status", lite_html)
        self.assertIn(".chat-panel", lite_style)
        self.assertIn("height: calc(100dvh - 154px", lite_style)
        self.assertIn("-webkit-overflow-scrolling: touch", lite_style)
        self.assertIn("manualScrollPauseUntil", lite_app)
        self.assertIn('serve.add_argument("--lite"', cli_main)
        self.assertIn('("--lite", args.lite)', cli_main)
        self.assertIn("lite=args.lite", client_cli)

    def test_password_inputs_are_password_type(self) -> None:
        self.assertIn('id="password"', self.app)
        self.assertIn('data-secret-field="password" type="password"', self.app)
        self.assertIn('id="totp-seed"', self.app)
        self.assertIn('data-secret-field="totp_seed" type="password"', self.app)

    def test_vault_save_is_request_scoped_and_user_confirmed(self) -> None:
        self.assertIn('request.status !== "pending"', self.app)
        self.assertIn("vaultSaveAllowed = request.save_to_vault === true", self.app)
        self.assertIn('data-secret-field="save_to_vault" ${vaultSaveAllowed ? "checked" : "disabled"}', self.app)
        self.assertIn("Boolean(vaultSaveAllowed && saveToVault.checked)", self.app)

    def test_credential_form_uses_request_scoped_field_labels(self) -> None:
        self.assertIn("credentialLabel", self.app)
        self.assertIn("credentialFieldRequested", self.app)
        self.assertIn("request.structured_details?.credential_labels", self.app)
        self.assertIn("GitHub PAT", (self.root / "docs" / "flask-env-credential.md").read_text())

    def test_challenge_no_bypass_explanation_present(self) -> None:
        self.assertIn("does not bypass CAPTCHA/MFA/Passkey/WebAuthn/3DS", self.html)
        self.assertIn("Complete the challenge yourself", self.app)
        self.assertIn("No challenge answer is submitted to OmniDoer", self.app)
        self.assertIn('if (isVisualChallenge)', self.app)

    def test_takeover_explanation_present(self) -> None:
        self.assertIn("Agent paused", self.html)
        self.assertIn("User in control", self.html)
        self.assertIn("Pause Agent", self.html)
        self.assertIn("Continue Agent", self.html)
        self.assertIn("Registration Handoff", self.html)
        self.assertIn("does not automate fake or bulk registration", self.html)

    def test_payment_fields_present(self) -> None:
        for label in (
            "Merchant",
            "Amount",
            "Currency",
            "Origin",
            "Recipient",
            "Shipping address",
            "Billing method summary",
            "Subscription / renewal",
            "Refund / cancellation terms",
            "Final button text",
            "Review fingerprint",
            "After approval",
        ):
            self.assertIn(label, self.html)

    def test_app_uses_webcrypto_and_request_api(self) -> None:
        app = (static_root() / "app.js").read_text()
        self.assertIn("crypto.subtle", app)
        self.assertIn("/api/requests", app)
        self.assertIn("submitEncrypted", app)
        self.assertIn("web-p256-v1", app)

    def test_requests_default_to_open_items(self) -> None:
        self.assertIn("language-select", self.html)
        self.assertIn("LANGUAGE_OPTIONS", self.app)
        for code in ('"es"', '"fr"', '"de"', '"ja"', '"ko"'):
            self.assertIn(code, self.app)
        self.assertIn("const I18N", self.app)
        self.assertIn("待处理请求", self.app)
        self.assertIn('data-filter="open" class="active"', self.app)
        self.assertIn("function isOpenRequest", self.app)
        self.assertIn('return ["pending", "user_control"].includes(request.status);', self.app)
        self.assertIn("attentionTitle", self.app)
        self.assertIn("attention-strip", self.app)
        self.assertIn("updateAttentionStrip", self.app)
        self.assertIn("updateMobileAttentionSignals", self.app)
        self.assertIn("BASE_DOCUMENT_TITLE", self.app)
        self.assertIn("navigator.vibrate([80])", self.app)
        self.assertIn("document.title = `(${openCount}) ${BASE_DOCUMENT_TITLE}`", self.app)
        self.assertIn("primaryOpenRequest", self.app)
        self.assertIn("requestAttentionRank", self.app)
        self.assertIn("document.body.dataset.hasAttention", self.app)
        self.assertIn("No open requests match this filter.", self.app)
        style = (static_root() / "style.css").read_text()
        self.assertIn("request-closed", style)
        self.assertIn(".attention-strip", style)
        self.assertIn('body[data-has-attention="true"] #task-panel', style)

    def test_overview_panel_surfaces_integrated_control_state(self) -> None:
        self.assertIn('href="#overview-panel"', self.html)
        self.assertIn('id="overview-panel"', self.html)
        self.assertIn('id="overview-next-card"', self.html)
        self.assertIn('id="overview-primary-action"', self.html)
        self.assertIn('id="overview-sync-approval"', self.html)
        self.assertIn('id="overview-sync-confirm"', self.html)
        self.assertIn('id="overview-sync-card"', self.html)
        self.assertIn('id="overview-requests-card"', self.html)
        self.assertIn('id="overview-browser-card"', self.html)
        self.assertIn('id="overview-chat-card"', self.html)
        self.assertIn('id="overview-pairing-card"', self.html)
        self.assertIn("navOverview", self.app)
        self.assertIn('"overview-panel"', self.app)
        self.assertIn('const DEFAULT_PANEL_ID = "overview-panel"', self.app)
        self.assertIn("updateOverview", self.app)
        self.assertIn("overviewRuntimeState", self.app)
        self.assertIn("setOverviewAction", self.app)
        self.assertIn("runOverviewAction", self.app)
        self.assertIn("updateOverviewSyncApprovalCard", self.app)
        self.assertIn("updateOverviewSyncApprovalButtons", self.app)
        self.assertIn("approvePendingSyncRequestFromOverview", self.app)
        self.assertIn('primaryAction: "sync-approve"', self.app)
        self.assertIn('explicitApprovalConfirmationPayload(request)', self.app)
        self.assertIn('document.querySelectorAll(".overview-card")', self.app)
        self.assertIn("pendingConsoleRestartRequest()", self.app)
        self.assertIn("findActiveTakeoverRequest(cachedRequests)", self.app)
        self.assertIn("activeBrowserContext()", self.app)
        self.assertIn("browserContextRecency", self.app)
        self.assertIn(".filter((context) => context.active && context.current_url)", self.app)
        style = (static_root() / "style.css").read_text()
        self.assertIn(".overview-panel", style)
        self.assertIn(".overview-hero", style)
        self.assertIn(".overview-grid", style)
        self.assertIn(".overview-sync-approval", style)
        self.assertIn(".overview-card[data-state=\"active\"]", style)

    def test_request_urls_are_clickable(self) -> None:
        self.assertIn('value.startsWith("https://")', self.app)
        self.assertIn('link.target = "_blank"', self.app)
        self.assertIn('link.rel = "noopener noreferrer"', self.app)

    def test_secure_form_drafts_survive_request_rerender(self) -> None:
        self.assertIn("captureRequestDrafts", self.app)
        self.assertIn("restoreRequestDrafts", self.app)
        self.assertIn("requestDraftInputs", self.app)
        self.assertIn("item.dataset.requestId = request.request_id", self.app)
        self.assertIn("activeInput.focus({ preventScroll: true })", self.app)

    def test_approval_confirmation_drafts_survive_request_rerender(self) -> None:
        self.assertIn("approvalConfirmationDrafts", self.app)
        self.assertIn("setApprovalDraftChecked", self.app)
        self.assertIn("approvalDraftChecked(request, \"request-card\")", self.app)
        self.assertIn("approvalDraftChecked(request, \"chat-sync\")", self.app)
        self.assertIn("approvalDraftChecked(request, \"overview-sync\")", self.app)
        self.assertIn("approvalDraftChecked(request, \"payment-panel\")", self.app)
        self.assertIn("clearApprovalDraftsForRequest(request.request_id)", self.app)
        self.assertIn("pruneApprovalDrafts(requests)", self.app)
        self.assertIn("pruneApprovalDrafts(cachedRequests)", self.app)

    def test_external_handoff_has_clear_controls(self) -> None:
        self.assertIn("externalHandoffNote", self.app)
        self.assertIn("openCurrentUrl", self.app)
        self.assertIn("releaseControl", self.app)
        self.assertIn("pauseAgent", self.app)
        self.assertIn("takeoverPausePrompt", self.app)
        self.assertIn("if (!request.browser_context_id)", self.app)
        self.assertIn("button-link", self.app)

    def test_task_panel_uses_local_queue_not_direct_model_api(self) -> None:
        self.assertIn("Chat", self.html)
        self.assertIn("Control Client does not call OpenAI APIs or models directly", self.html)
        self.assertIn("local Agent reads queued messages", self.html)
        app = (static_root() / "app.js").read_text()
        self.assertIn("runtimeWaitingForConsoleRestart", app)
        self.assertIn("runtimeModeAttached", app)
        self.assertIn("runtimeModeLegacyRelay", app)
        self.assertIn("runtimeModeServerOnly", app)
        self.assertIn("runtimeLegacyRelayActive", app)
        self.assertIn("runtimeLegacyRelayPause", app)
        self.assertIn("runtimeNativeBridgeReady", app)
        self.assertIn("runtimeNativeBridgeNotReady", app)
        self.assertIn("runtimeMcpSidecarNeedsRestart", app)
        self.assertIn("chatSessionServerOnlyTitle", app)
        self.assertIn("chatSessionAttachedTitle", app)
        self.assertIn("chatSessionLegacyTitle", app)
        self.assertIn("chatSyncDiagnosticNative", app)
        self.assertIn("chatSyncDiagnosticMcpStale", app)
        self.assertIn("chatSyncDiagnosticLegacy", app)
        self.assertIn("chatSyncDiagnosticStaleBinary", app)
        self.assertIn("chatSyncDiagnosticWaiting", app)
        self.assertIn("runner.sync_diagnostics", app)
        self.assertIn("runner.active_tui_process_bridge", app)
        self.assertIn("runner.mcp_sidecar", app)
        self.assertIn("restart_browser_takeover_relay_available", app)
        self.assertIn("sendToCurrentCli", app)
        self.assertIn("sendToCurrentConsole", app)
        self.assertIn("sendUnavailable", app)
        self.assertIn("chatPlaceholderLegacy", app)
        self.assertIn("chatPlaceholderUnavailable", app)
        self.assertIn("chatDeliveredToConsole", app)
        self.assertIn("live_console_delivery", app)
        self.assertIn("chatQueuedForBridge", app)
        self.assertIn("updateChatSessionStatus", app)
        self.assertIn("cachedRuntimeStatus", app)
        self.assertIn('document.body.dataset.chatSessionState', app)
        self.assertIn('document.body.dataset.chatSendMode', app)
        self.assertIn('input.disabled = !canEditDraft', app)
        self.assertIn('input.dataset.sendBlocked = canSend ? "false" : "true"', app)
        self.assertIn('send.disabled = false', app)
        self.assertIn('send.classList.toggle("soft-disabled", canEditDraft && !canSend)', app)
        self.assertIn('files.disabled = false', app)
        self.assertIn('fileLabel.classList.toggle("disabled", !canSend)', app)
        self.assertIn("pendingChatMessages", app)
        self.assertIn('id="chat-session-status"', self.html)
        self.assertIn('id="chat-session-restart"', self.html)
        self.assertIn("runner.native_console_bridge", app)
        self.assertIn("runtimeActiveConsoleNeedsBinaryRestart", app)
        self.assertIn("legacyRelay.capabilities?.interrupt_on_pause", app)
        self.assertIn("runner.waiting_for_tui_bridge", app)
        self.assertIn("runner.restart_command", app)
        self.assertIn("runner.legacy_tui_relay", app)
        self.assertIn("runtime-command", app)
        self.assertIn("runtime-command-row", app)
        self.assertIn("runtime-copy-command", app)
        self.assertIn("runtime-restart-bridge", app)
        self.assertIn("copyRuntimeCommand", app)
        self.assertIn("restartConsoleBridge", app)
        self.assertIn("/api/console/restart-bridge/request", app)
        self.assertIn("restartBridgeApprovalRequested", app)
        self.assertIn("reviewSyncRequest", app)
        self.assertIn("chatSyncApprovalPending", app)
        self.assertIn('id="chat-sync-approval"', self.html)
        self.assertIn('id="chat-sync-approval-expires"', self.html)
        self.assertIn("syncApprovalTitle", app)
        self.assertIn("takeoverRelayApprovalTitle", app)
        self.assertIn("takeoverRelayApprovalDetail", app)
        self.assertIn("syncApprovalExpires", app)
        self.assertIn("takeoverRelayConfirmText", app)
        self.assertIn("SYNC_REQUEST_RENEW_WINDOW_MS", app)
        self.assertIn("syncRequestNeedsRefresh", app)
        self.assertIn("requestConsoleRestartApproval", app)
        self.assertIn("openOrRefreshPendingSyncRequest", app)
        self.assertIn("syncApprovalApprove", app)
        self.assertIn("takeoverRelayApprove", app)
        self.assertIn("consoleRestartIsTakeoverRelay", app)
        self.assertIn("consoleRestartCopyKeys", app)
        self.assertIn("approvePendingSyncRequestFromChat", app)
        self.assertIn("denyPendingSyncRequestFromChat", app)
        self.assertIn("updateChatSyncApprovalCard", app)
        self.assertIn("AUTO_SYNC_REQUEST_COOLDOWN_MS", app)
        self.assertIn("ensureChatSyncApprovalRequest", app)
        self.assertIn("maybeAutoOpenSyncApprovalCard", app)
        self.assertIn("autoOpenedSyncRequestId", app)
        self.assertIn('activatePanel("task-panel", { persist: false })', app)
        self.assertIn('activePanel === "requests-panel" || activePanel === "takeover-panel" || takeoverIsActive()', app)
        self.assertIn("autoSyncRequestInFlight", app)
        self.assertIn("cachedPairingAuthenticated", app)
        self.assertIn("upsertCachedRequest(payload.request)", app)
        self.assertIn("ensureChatSyncApprovalRequest(runner)", app)
        self.assertIn('setButtonText("#chat-sync-approval-approve", "syncApprovalApprove")', app)
        self.assertIn("pendingConsoleRestartRequest", app)
        self.assertIn("openPendingSyncRequest", app)
        self.assertIn("focusRequestCard", app)
        self.assertIn("consoleRestartConfirmText", app)
        self.assertIn("console_restart", app)
        self.assertIn("explicitApprovalConfirmationPayload", app)
        self.assertIn("copyCommand", app)
        self.assertIn("copyCodeBlock", app)
        self.assertIn("copyTextToClipboard", app)
        self.assertIn("runtimeQuotaLabel", app)
        self.assertIn("runtimeQuotaValues", app)
        self.assertIn("runtimeQuotaText", app)
        self.assertIn("formatPercent", app)
        self.assertIn("codex_5h_percent_left", app)
        self.assertIn("codex_weekly_percent_left", app)
        self.assertIn('id="runtime-quota"', app)
        self.assertIn('mode = quotaText', app)
        self.assertIn('state === "attached" ? runtimeQuotaText(cachedRuntimeStatus)', app)
        self.assertIn("isInternalAutoStatusMessage", app)
        self.assertIn("CHAT_CACHE_KEY_PREFIX", app)
        self.assertIn("restoreChatTimelineCache", app)
        self.assertIn("persistChatTimelineCache", app)
        self.assertIn("formatChatTimestamp", app)
        self.assertIn("CHAT_RETENTION_MS", app)
        self.assertIn("pruneChatTimelineForRetention", app)
        self.assertIn("20260605-tmuxfix", self.html)
        self.assertIn("<title>OmniDoer</title>", self.html)
        self.assertIn("markdown-copy-button", app)
        self.assertIn("chatSendInFlight", app)
        self.assertIn("forceChatScrollToBottom", app)
        self.assertIn("chatFeedNearBottom", app)
        self.assertIn("restartBridge", app)
        self.assertIn("restartAgentForTakeover", app)
        self.assertIn("enableCurrentSessionSync", app)
        self.assertIn("restartBridgeConfirmDetailed", app)
        self.assertIn("restartBridgeChecking", app)
        self.assertIn("restartBridgeActivated", app)
        self.assertIn("restartBridgeStillWaiting", app)
        self.assertIn("runnerNeedsCurrentSessionSync", app)
        self.assertIn("runnerCanRestartCurrentConsole", app)
        self.assertIn("restart_current_console_available", app)
        self.assertIn("activation_action", app)
        self.assertIn("monitorBridgeActivation", app)
        self.assertIn("stopBridgeActivationMonitor", app)
        self.assertIn("bridgeActivationDeadline", app)
        self.assertIn('classList.toggle("primary-action"', app)
        self.assertIn(".request-focus", (static_root() / "style.css").read_text())
        self.assertIn("runner.tui_bridge_active", app)
        self.assertIn("document.body.dataset.runtimeState", app)
        self.assertIn("const PANEL_IDS", app)
        self.assertIn("function activatePanel", app)
        self.assertIn("setupPanelNavigation", app)
        self.assertIn("updateRequestsTabBadge", app)
        style = (static_root() / "style.css").read_text()
        self.assertIn("section.control-panel[hidden]", style)
        self.assertIn(".section-tabs a.active", style)
        self.assertIn(".section-tabs a.has-open-requests::after", style)
        self.assertIn('body[data-runtime-state="waiting_for_tui_bridge"]', style)
        self.assertIn('body[data-runtime-state="legacy_tui_relay"]', style)
        self.assertIn('body[data-runtime-state="waiting_for_tui_bridge"] #task-panel', style)
        self.assertIn('body[data-runtime-state="legacy_tui_relay"] #task-panel', style)
        self.assertIn("/api/chat/messages", app)
        self.assertIn("sendChatMessage", app)
        self.assertIn("startChatWebSocket", app)
        self.assertIn("/api/ws/chat", app)
        self.assertIn("/api/chat/events?stream=1", app)
        self.assertIn("snapshots=1200&interval=0.75", app)
        self.assertIn("interval=0.75", app)
        self.assertIn("renderChatRecord", app)
        self.assertIn("compactChatActivityRecords", app)
        self.assertIn("shortChatId", app)
        self.assertIn("chatRecordChunks", app)
        self.assertIn("delta_count", app)
        self.assertIn("renderLegacyTerminal", app)
        self.assertIn("renderLiveConsole", app)
        self.assertIn('id="chat-live-console"', self.html)
        self.assertIn('role="log"', self.html)
        self.assertIn('aria-live="polite"', self.html)
        self.assertIn("pre.scrollTop = pre.scrollHeight", app)
        self.assertIn("chatConversationTitle", app)
        self.assertIn("chatActivityTitle", app)
        self.assertIn('conversation.className = "chat-conversation"', app)
        self.assertIn('activity.className = "chat-activity"', app)
        self.assertIn('list.append(conversation)', app)
        self.assertIn("cachedChatRecords", app)
        self.assertIn("cachedChatTerminal", app)
        self.assertIn("payload.terminal", app)
        self.assertIn("chatPayloadFingerprint", app)
        self.assertIn("scheduleRealtimeRefreshFromChat", app)
        self.assertIn("Promise.allSettled", app)
        self.assertIn("chatMessagesLoadPromise", app)
        self.assertIn("runtimeStatusLoadPromise", app)
        self.assertIn("CHAT_COMPACT_LIMIT", app)
        self.assertIn("compact=1", app)
        self.assertIn("API_FETCH_TIMEOUT_MS", app)
        self.assertIn("setChatFeedFallback", app)
        self.assertIn("loadRuntimeStatus()", app)
        self.assertIn("loadBrowserContexts()", app)
        self.assertIn("lastChatPayloadFingerprint", app)
        self.assertIn("renderChatTimeline(cachedChatMessages, cachedChatRecords, cachedChatTerminal)", app)
        self.assertIn("record_type", app)
        self.assertIn("chatRecordTerminal", app)
        self.assertIn("chatRecordReasoning", app)
        self.assertIn("chatRecordTerminalInput", app)
        self.assertIn("chatRecordTerminalSnapshot", app)
        self.assertIn("chatRecordTerminalDelta", app)
        self.assertIn('terminal: t("chatRecordTerminal")', app)
        self.assertIn('reasoning: t("chatRecordReasoning")', app)
        self.assertIn('terminal_input: t("chatRecordTerminalInput")', app)
        self.assertIn('id="chat-files"', self.html)
        self.assertIn('id="chat-input-label-text"', self.html)
        self.assertIn('class="chat-input-shell"', self.html)
        self.assertIn('id="chat-session-select"', self.html)
        self.assertNotIn('id="create-chat-session"', self.html)
        self.assertNotIn('id="close-chat-session"', self.html)
        self.assertIn('id="chat-files-label" class="file-button icon-button"', self.html)
        self.assertIn('id="send-chat-message" class="icon-button"', self.html)
        self.assertIn('class="control-icon"', self.html)
        self.assertIn("/api/chat/attachments", app)
        self.assertIn("FormData", app)
        self.assertIn("formatFileSize", app)
        self.assertIn("setIconControlLabel", app)
        self.assertIn('setIconControlLabel("#chat-files-label"', app)
        self.assertIn('setIconControlLabel("#send-chat-message"', app)
        self.assertIn("renderChatSessions", app)
        self.assertIn("activateChatSession", app)
        self.assertIn("mergePendingChatMessages", app)
        self.assertIn("addPendingChatMessage", app)
        self.assertIn("/api/chat/sessions", app)
        self.assertIn("CHAT_CACHE_KEY_PREFIX", app)
        self.assertIn("appendMarkdown", app)
        self.assertIn("appendInlineMarkdown", app)
        self.assertIn("safeMarkdownHref", app)
        self.assertIn('appendMarkdown(item, message.text || " ", "chat-message-text")', app)
        self.assertIn("renderToolRecord", app)
        self.assertIn("renderToolStatusLine", app)
        self.assertIn("currentTurnToolStats", app)
        self.assertIn("assistantMessageCount", app)
        self.assertIn("Math.max(reasoningRecordCount, assistantMessageCount)", app)
        self.assertIn("chatTurnStatus", app)
        self.assertIn("chatRecordMirrorsVisibleMessage", app)
        self.assertIn('["message", "delta", "status"].includes(record.record_type)', app)
        self.assertIn("toolOutputSummary", app)
        self.assertIn("compactToolActivityRecords", app)
        self.assertIn("toolGroupOutputSummary", app)
        self.assertIn('"tool_group"', app)
        self.assertIn("visibleActivityRecords", app)
        self.assertIn('["tool_call", "tool_output", "tool_group"].includes(record.record_type)', app)
        self.assertIn("storedPairingLikelyPresent", app)
        self.assertIn('runtimeState = "checking_pairing"', app)
        self.assertIn('state = "checking"', app)
        self.assertIn('send.setAttribute("aria-label", t(sendKey))', app)
        self.assertIn("send.title = t(sendKey)", app)
        self.assertIn('runtimeStatusPanel.setAttribute("aria-label"', app)
        self.assertIn('setNodeText("#chat-input-label-text"', app)
        self.assertNotIn('setNodeText("#chat-input-label"', app)
        self.assertNotIn('setButtonText("#send-chat-message"', app)
        self.assertIn("chat-file-chip", (static_root() / "style.css").read_text())
        self.assertIn(".chat-input-shell", (static_root() / "style.css").read_text())
        self.assertIn(".icon-button", (static_root() / "style.css").read_text())
        self.assertIn(".control-icon", (static_root() / "style.css").read_text())
        self.assertIn(".status-strip #runtime-mode::before", (static_root() / "style.css").read_text())
        self.assertIn(".status-strip #runtime-detail {\n  display: none;", (static_root() / "style.css").read_text())
        self.assertIn(".runtime-quota", (static_root() / "style.css").read_text())
        self.assertIn(".runtime-primary-line", (static_root() / "style.css").read_text())
        self.assertIn('body[data-runtime-state="tui_bridge_active"] .runtime-quota', (static_root() / "style.css").read_text())
        self.assertIn(".chat-panel-header {\n  grid-row: 1;\n  display: none;", (static_root() / "style.css").read_text())
        self.assertIn("min-height: 24px", (static_root() / "style.css").read_text())
        self.assertIn(".chat-record-status .chat-message-header", (static_root() / "style.css").read_text())
        self.assertIn(".chat-record-status .chat-message-meta", (static_root() / "style.css").read_text())
        self.assertIn(".chat-record .chat-message-text", (static_root() / "style.css").read_text())
        self.assertIn(".chat-message-text.markdown-text", (static_root() / "style.css").read_text())
        self.assertIn(".markdown-code-block", (static_root() / "style.css").read_text())
        self.assertIn(".markdown-copy-button", (static_root() / "style.css").read_text())
        self.assertIn("width: auto;", (static_root() / "style.css").read_text())
        self.assertIn(".markdown-text pre code", (static_root() / "style.css").read_text())
        self.assertIn(".chat-tool-summary", (static_root() / "style.css").read_text())
        self.assertIn(".chat-tool-status-line", (static_root() / "style.css").read_text())
        self.assertIn(".chat-tool-status-line .chat-turn-status-text", (static_root() / "style.css").read_text())
        self.assertIn("@keyframes chatToolPulse", (static_root() / "style.css").read_text())
        self.assertIn(".chat-tool-full", (static_root() / "style.css").read_text())
        self.assertNotIn('body[data-active-panel="task-panel"] .app-header img', (static_root() / "style.css").read_text())
        self.assertIn("height: calc(100dvh - 92px)", (static_root() / "style.css").read_text())
        self.assertIn(".chat-session-status p", (static_root() / "style.css").read_text())
        self.assertIn("runtime-copy-button", (static_root() / "style.css").read_text())
        self.assertIn("runtime-restart-button", (static_root() / "style.css").read_text())
        self.assertIn(".runtime-restart-button.primary-action", (static_root() / "style.css").read_text())
        self.assertIn(".chat-session-restart.primary-action", (static_root() / "style.css").read_text())
        self.assertIn("chat-session-status", (static_root() / "style.css").read_text())
        self.assertIn('data-session-state="checking"', self.html)
        self.assertIn("grid-template-rows: auto auto auto minmax(0, auto) minmax(0, auto) minmax(0, auto) minmax(96px, 1fr) auto", (static_root() / "style.css").read_text())
        self.assertIn("max-height: min(34svh, 260px)", (static_root() / "style.css").read_text())
        self.assertIn("max-height: min(30svh, 240px)", (static_root() / "style.css").read_text())
        self.assertIn("chat-sync-approval-card", (static_root() / "style.css").read_text())
        self.assertIn(".file-button.disabled", (static_root() / "style.css").read_text())
        self.assertIn("chat-conversation", (static_root() / "style.css").read_text())
        self.assertIn("chat-activity", (static_root() / "style.css").read_text())
        self.assertIn("chat-live-console", (static_root() / "style.css").read_text())
        self.assertIn("chat-record-delta", (static_root() / "style.css").read_text())
        self.assertIn("chat-record-terminal", (static_root() / "style.css").read_text())
        self.assertIn("chat-terminal-snapshot", (static_root() / "style.css").read_text())

    def test_chat_composer_has_slash_command_completion(self) -> None:
        style = (static_root() / "style.css").read_text()
        self.assertIn('id="chat-command-menu"', self.html)
        self.assertIn('role="listbox"', self.html)
        self.assertIn('aria-controls="chat-command-menu"', self.html)
        self.assertIn("const CHAT_COMMANDS", self.app)
        self.assertIn('command: "/status"', self.app)
        self.assertIn('command: "/resume"', self.app)
        self.assertIn("chatCommandContext", self.app)
        self.assertIn("chatTextIsCliCommand", self.app)
        self.assertIn("matchingChatCommands", self.app)
        self.assertIn("updateChatCommandMenu", self.app)
        self.assertIn("handleChatCommandKeydown", self.app)
        self.assertIn("applyChatCommandCompletion", self.app)
        self.assertIn("control_cli_", self.app)
        self.assertIn("chatCliCommandQueued", self.app)
        self.assertIn("slashCommandsHint", self.app)
        self.assertIn("chatCommandMenuIndex", self.app)
        self.assertIn(".chat-command-menu", style)
        self.assertIn(".chat-command-option", style)
        self.assertIn('.chat-command-option[aria-selected="true"]', style)

    def test_pairing_panel_and_cloud_csrf_contract_present(self) -> None:
        self.assertIn("Pair Device", self.html)
        self.assertIn("Only pair devices you control", self.html)
        self.assertIn("Server URL", self.html)
        self.assertIn("This device", self.html)
        self.assertIn("Broker fingerprint", self.html)
        self.assertIn("Web broker fingerprint", self.html)
        self.assertIn("Remaining uses", self.html)
        self.assertIn("Devices / Sessions", self.html)
        self.assertIn("Forget Local Pairing", self.html)
        app = (static_root() / "app.js").read_text()
        self.assertIn("/api/pairing/", app)
        self.assertIn("loadPairingDetails", app)
        self.assertIn("pairing_id", app)
        self.assertIn("/api/pair", app)
        self.assertIn("/api/auth/check", app)
        self.assertIn("/api/devices", app)
        self.assertIn("/api/sessions", app)
        self.assertIn("revokeDevice", app)
        self.assertIn("revokeSession", app)
        self.assertIn('signedFetch("/api/broker-key"', app)
        self.assertIn("omnidoer_device_id", app)
        self.assertIn("omnidoer_session_id", app)
        self.assertIn("x-omnidoer-csrf", app)
        self.assertIn("x-omnidoer-session-id", app)
        self.assertIn("x-omnidoer-device-sig", app)
        self.assertIn("omnidoer-device-v1", app)
        self.assertIn("signedFetch", app)
        self.assertIn("device_id", app)
        self.assertIn("expires_at", app)
        self.assertIn("storedPairingIdentity", app)
        self.assertIn("refreshPairingState", app)
        self.assertIn("forgetLocalPairing", app)
        self.assertIn("This browser stays paired long-term unless the session is revoked or browser data is cleared.", app)
        self.assertIn("6-digit pairing code", app)
        self.assertIn("device key stays in this browser after pairing", app)
        self.assertIn("normalizePairingCodeInput", app)
        self.assertIn("session cookie or signature was rejected", app)
        self.assertIn("Control Service reachable", app)
        self.assertIn("This browser is not paired yet", app)
        self.assertIn("cachedPairingAuthenticated", app)
        self.assertIn("modeRequiresPairing(status.mode) && !cachedPairingAuthenticated", app)
        self.assertIn("initialPairingCode", app)
        self.assertIn("initialPairingId", app)
        self.assertIn("autoPairFromInitialLink", app)
        self.assertIn("if (initialPairingCode)", app)
        self.assertIn("bootstrapControlClient", app)
        self.assertIn("refreshAuthenticatedData", app)
        self.assertIn("startAuthenticatedRealtime", app)
        self.assertIn("PAIRING_STEP_TIMEOUT_MS", app)
        self.assertIn("withTimeout(deviceKeyPair()", app)
        self.assertIn("pairingFailureMessage", app)
        self.assertIn("pairing_code_expired", app)
        self.assertIn("pairing-remaining-uses", app)
        self.assertIn("window.history.replaceState", app)

    def test_request_stream_uses_signed_fetch_not_eventsource(self) -> None:
        app = (static_root() / "app.js").read_text()
        self.assertIn("startRequestStream", app)
        self.assertIn("startRequestWebSocket", app)
        self.assertIn("new WebSocket", app)
        self.assertIn("/api/ws/requests", app)
        self.assertIn("deviceAuthSubprotocol", app)
        self.assertIn("omnidoer-v1.", app)
        self.assertIn("/api/events?stream=1", app)
        self.assertIn("snapshots=1200&interval=2", app)
        self.assertIn("ReadableStream", app)
        self.assertIn("signedFetch(\"/api/events?stream=1", app)
        self.assertNotIn("new EventSource", app)

    def test_takeover_ui_sends_rich_input_events(self) -> None:
        app = (static_root() / "app.js").read_text()
        for event_type in ("double_click", "drag", "long_press", "scroll", "type", "key"):
            self.assertIn(f'event_type: "{event_type}"', app)
        self.assertIn("TAKEOVER_DOUBLE_TAP_MS", app)
        self.assertIn("queueTakeoverTap", app)
        self.assertIn("sameTakeoverTapTarget", app)
        self.assertIn("clearPendingTakeoverTap", app)
        self.assertIn("refreshActiveTakeoverFrame", app)
        self.assertIn("releaseActiveTakeover", app)
        self.assertIn("Agent paused - user control active", app)
        self.assertIn("Touch, keyboard, and text input are routed to the controlled browser only", app)
        self.assertIn("takeoverAgentPausedStatus", app)
        self.assertIn('t("takeoverAgentPausedStatus")', app)
        self.assertIn("takeoverInputStateActive", app)
        self.assertIn('t("takeoverInputStateActive")', app)
        self.assertIn("takeover-status-label", self.html)
        self.assertIn("takeover-current-url", self.html)
        self.assertIn("takeover-frame-connection", self.html)
        self.assertIn("takeover-frame-freshness", self.html)
        self.assertIn("takeover-frame-profile", self.html)
        self.assertIn("takeover-frame-zoom", self.html)
        self.assertIn("request-takeover-pause", self.html)
        self.assertIn('id="active-takeover-text"', self.html)
        self.assertIn('id="send-active-takeover-text"', self.html)
        self.assertIn('id="send-active-takeover-enter"', self.html)
        self.assertIn("takeoverTabLive", app)
        self.assertIn("takeoverTabPreview", app)
        self.assertIn("updateTakeoverTabBadge", app)
        self.assertIn("updateBrowserHandoffState", app)
        self.assertIn("browserHandoffPreviewTitle", app)
        self.assertIn("browserHandoffActiveTitle", app)
        self.assertIn("browserHandoffView", app)
        self.assertIn("browserHandoffPause", app)
        self.assertIn("browserHandoffContinue", app)
        self.assertIn('id="browser-handoff-strip"', self.html)
        self.assertIn('id="browser-handoff-view"', self.html)
        self.assertIn('id="browser-handoff-pause"', self.html)
        self.assertIn('id="browser-handoff-continue"', self.html)
        self.assertIn('browserHandoffViewButton.onclick = () => activatePanel("takeover-panel")', app)
        self.assertIn("maybeAutoOpenTakeoverPanel", app)
        self.assertIn('activatePanel("takeover-panel", { persist: false })', app)
        self.assertIn("autoOpenedTakeoverRequestId", app)
        self.assertIn("autoOpenedPreviewContextId", app)
        self.assertIn("context.browser_context_id", app)
        self.assertIn("browserHandoffPauseButton.onclick = () => requestTakeoverPause()", app)
        self.assertIn("browserHandoffContinueButton.onclick = () => releaseActiveTakeover()", app)
        self.assertIn('a[href="#takeover-panel"]', app)
        self.assertIn("has-active-takeover", app)
        self.assertIn("has-browser-preview", app)
        self.assertIn('document.body.dataset.browserHandoffState', app)
        self.assertIn("updateBrowserHandoffState(request, context)", app)
        self.assertIn("takeoverReleasePrompt", app)
        self.assertIn("takeoverReleased", app)
        self.assertIn('setStatus(t("takeoverReleased"), t("takeoverReleasedDetail"))', app)
        self.assertIn('activatePanel("task-panel", { persist: false })', app)
        self.assertIn("upsertCachedRequest(payload);", app)
        self.assertIn("syncTakeoverPanel(cachedRequests);", app)
        self.assertIn("control_continue_", app)
        self.assertIn("agent_continue", app)
        self.assertIn('release.onclick = () => releaseActiveTakeover()', app)
        self.assertIn('controls.querySelector("[data-action=\'release\']").onclick = () => releaseActiveTakeover()', app)
        self.assertNotIn('release.onclick = () => postAction(request, "release")', app)
        self.assertIn("runtime-pause-agent", app)
        self.assertIn("quick-pause-button", app)
        self.assertIn("quick-continue-button", app)
        self.assertIn("updateAgentControlButtons", app)
        self.assertIn("refreshRequestDependentUi", app)
        self.assertIn("function refreshRequestDependentUi", app)
        self.assertIn("applyRequestEvent(payload)", app)
        self.assertIn("updateActiveTakeoverTextControls", app)
        self.assertIn("sendActiveTakeoverText", app)
        self.assertIn("sendActiveTakeoverEnter", app)
        self.assertIn(".takeover-text-row", (static_root() / "style.css").read_text())
        self.assertIn('quick.dataset.agentAction = isActive ? "release" : "pause"', app)
        self.assertIn("takeoverIsActive()", app)
        self.assertIn("releaseActiveTakeover();", app)
        self.assertIn("setPauseButtonsDisabled", app)
        self.assertIn('document.querySelector("#runtime-pause-agent")', app)
        self.assertIn('document.querySelector("#request-takeover-pause")', app)
        self.assertIn("Refresh Frame", self.html)
        self.assertIn("zoom-out-takeover-frame", self.html)
        self.assertIn("zoom-reset-takeover-frame", self.html)
        self.assertIn("zoom-in-takeover-frame", self.html)
        self.assertIn("pan-takeover-frame", self.html)
        self.assertIn("refreshFrame", app)
        self.assertIn('setButtonText("#refresh-takeover-frame", "refreshFrame")', app)
        self.assertIn('zoomOut.setAttribute("aria-label", t("zoomOut"))', app)
        self.assertIn("Text to controlled browser", app)
        self.assertIn("installTakeoverPointerHandlers", app)
        self.assertIn("activeTouchPointers", app)
        self.assertIn("pinchGesture", app)
        self.assertIn("Pinch zooming local browser frame. Input is not sent to the controlled browser.", app)
        self.assertIn('t("takeoverPinchZooming")', app)
        self.assertIn("takeoverHasVisibleFrame", app)
        self.assertIn("zoomOut.disabled = !hasFrame || !zoomed", app)
        self.assertIn("clearTakeoverPointerHandlers", app)
        self.assertIn("stream.onpointerdown = null", app)
        self.assertIn("const actionResponse = await postAction(request, \"release\")", app)
        self.assertIn("return response", app)
        self.assertIn("startTakeoverFramePolling", app)
        self.assertIn("startTakeoverFrameWebSocket", app)
        self.assertIn("/api/ws/requests/", app)
        self.assertIn("takeover_frame", app)
        self.assertIn("startBrowserPreviewWebSocket", app)
        self.assertIn("/api/ws/browser/contexts/", app)
        self.assertIn("/api/ws/browser/contexts", app)
        self.assertIn("/api/browser/contexts/events?stream=1", app)
        self.assertIn("startBrowserContextWebSocket", app)
        self.assertIn("applyBrowserContextsEvent", app)
        self.assertIn("browser_contexts", app)
        self.assertIn("browser_context_frame", app)
        self.assertIn("closeBrowserPreviewWebSocket", app)
        self.assertIn("requestTakeoverPause", app)
        self.assertIn("PENDING_TAKEOVER_PAUSE_TTL_MS", app)
        self.assertIn("pendingTakeoverPauseClientMessageId", app)
        self.assertIn("maybeAutoStartPendingTakeover", app)
        self.assertIn("createBrowserTakeoverFromContext", app)
        self.assertIn("maybeAutoStartPendingTakeover()", app)
        self.assertIn("notifyAgent: false", app)
        self.assertIn("control_pause_", app)
        self.assertIn("notify_agent", app)
        self.assertIn("agent_pause", app)
        self.assertIn("postChatMessage", app)
        self.assertIn("/api/browser/contexts", app)
        self.assertIn("loadBrowserContexts", app)
        self.assertIn("activeBrowserReady", app)
        self.assertIn("activeBrowserPreview", app)
        self.assertIn("browserRelayHealthText", app)
        self.assertIn("overviewBrowserReadinessText", app)
        self.assertIn("overviewBrowserRelayNeedsRestart", app)
        self.assertIn("runner.browser_takeover", app)
        self.assertIn("browserTakeoverRequiresSetup", app)
        self.assertIn("takeoverRelayNeedsRestartIdle", app)
        self.assertIn("takeoverReadinessText", app)
        self.assertIn("browserHandoffRelayLive", app)
        self.assertIn("browserHandoffRelayPendingInput", app)
        self.assertIn("relay_health", app)
        self.assertIn("/api/browser/contexts/${encodeURIComponent(context.browser_context_id)}/frame", app)
        self.assertIn("startBrowserPreviewPolling", app)
        self.assertIn("stopBrowserPreviewPolling", app)
        self.assertIn("BROWSER_PREVIEW_POLL_MS", app)
        self.assertIn("const TAKEOVER_FRAME_WS_SNAPSHOTS = 1200", app)
        self.assertIn("/api/browser/contexts/events?stream=1&snapshots=1200&interval=1", app)
        self.assertIn("${path}?snapshots=1200&interval=1", app)
        self.assertIn("connected - websocket", app)
        self.assertIn('t("takeoverConnectedWebSocket")', app)
        self.assertIn("Live frame WebSocket disconnected.", app)
        self.assertIn('t("takeoverWebSocketDisconnected")', app)
        self.assertIn("fetchTakeoverFrame", app)
        self.assertIn("TAKEOVER_FRAME_POLL_MS", app)
        self.assertIn("TAKEOVER_FRAME_WS_INTERVAL_SECONDS", app)
        self.assertIn("TAKEOVER_FRAME_PROFILE_DEFAULT", app)
        self.assertIn("TAKEOVER_FRAME_PROFILE_DATA_SAVER", app)
        self.assertIn("takeoverFrameProfile", app)
        self.assertIn("takeoverFrameQuery", app)
        self.assertIn("navigator.connection", app)
        self.assertIn("saveData", app)
        self.assertIn("profile: takeoverFrameProfile()", app)
        self.assertIn("frame.transport?.profile", app)
        self.assertIn("TAKEOVER_FRAME_AFTER_INPUT_MS", app)
        self.assertIn("scheduleTakeoverFrameRefresh", app)
        self.assertIn("takeoverFrameFetchInFlight", app)
        self.assertIn("takeoverFrameFetchQueued", app)
        self.assertIn("takeoverFrameVisibilityPaused", app)
        self.assertIn("pauseTakeoverFramePollingForVisibility", app)
        self.assertIn("resumeTakeoverFramePollingFromVisibility", app)
        self.assertIn("recoverAuthenticatedRealtimeAfterForeground", app)
        self.assertIn("resetAuthenticatedRealtimeStreams", app)
        self.assertIn("foregroundRealtimeRecovery", app)
        self.assertIn('document.addEventListener("visibilitychange", handleControlClientVisibilityChange)', app)
        self.assertIn("Frame polling paused while this Control Client is hidden", app)
        self.assertIn('t("takeoverPollingPausedHidden")', app)
        self.assertIn("Input is blocked while this Control Client is hidden or frame polling is paused", app)
        self.assertIn('t("takeoverInputHidden")', app)
        self.assertIn("quick-pause-button", (static_root() / "style.css").read_text())
        self.assertIn("quick-continue-button", (static_root() / "style.css").read_text())
        self.assertIn(".section-tabs a.has-active-takeover::after", (static_root() / "style.css").read_text())
        self.assertIn(".section-tabs a.has-browser-preview::after", (static_root() / "style.css").read_text())
        self.assertIn(".browser-handoff-strip", (static_root() / "style.css").read_text())
        self.assertIn("grid-template-rows: auto auto auto minmax(0, auto) minmax(0, auto) minmax(0, auto) minmax(96px, 1fr) auto", (static_root() / "style.css").read_text())
        self.assertIn("grid-template-rows: auto minmax(320px, 1fr) auto auto auto", (static_root() / "style.css").read_text())
        self.assertIn("body[data-active-panel=\"takeover-panel\"] .app-header", (static_root() / "style.css").read_text())
        self.assertIn("#takeover-panel .takeover-toolbar", (static_root() / "style.css").read_text())
        self.assertIn("return false;", app)
        self.assertIn("if (delivered) input.value = \"\";", app)
        self.assertIn("setInterval(() => fetchTakeoverFrame(request, stream), TAKEOVER_FRAME_POLL_MS)", app)
        self.assertIn("stopTakeoverFramePolling", app)
        self.assertIn("frame_id", app)
        self.assertIn("stream.dataset.frameId", app)
        self.assertIn("Input is bound to the frame currently visible here", app)
        self.assertIn('t("takeoverFrameReady")', app)
        self.assertIn("stale_takeover_frame", app)
        self.assertIn("TAKEOVER_FRAME_MAX_AGE_MS", app)
        self.assertIn("TAKEOVER_ZOOM_MAX", app)
        self.assertIn("setTakeoverFrameZoom", app)
        self.assertIn("applyTakeoverFrameZoom", app)
        self.assertIn("takeoverFramePanMode", app)
        self.assertIn("image.style.width", app)
        self.assertIn("Math.max(1, rect.width)", app)
        self.assertIn("takeoverFrameMisses", app)
        self.assertIn("markTakeoverFrameReconnect", app)
        self.assertIn("Keeping the last frame visible; stale frames remain blocked for input.", app)
        self.assertIn('t("takeoverKeepingLastFrame", message)', app)
        self.assertIn("frame-reconnecting", app)
        self.assertIn("takeoverFrameIsFresh", app)
        self.assertIn("Frame is stale; refreshing before input", app)
        self.assertIn('t("takeoverInputRefreshingStale")', app)
        self.assertIn("takeoverInputQueued", app)
        self.assertIn("takeoverInputStillPending", app)
        self.assertIn('updateTakeoverPanel(request, null, t("takeoverInputStillPending"))', app)
        self.assertIn("input-results/${encodeURIComponent(eventId)}?wait=6", app)
        self.assertIn('responsePayload.status || ""', app)
        self.assertIn('status === "event_queued"', app)
        self.assertIn("updateTakeoverFrameFreshness", app)
        self.assertIn("account_registration", app)
        self.assertIn('request.request_type === "human_takeover" || request.request_type === "account_registration"', app)
        self.assertIn("Registration Handoff", app)

    def test_payment_request_renderer_uses_structured_details(self) -> None:
        app = (static_root() / "app.js").read_text()
        self.assertIn("request.structured_details", app)
        self.assertIn("Agent prepared action", app)
        self.assertIn("Submit only after approval", app)
        self.assertIn("explicit_user_confirmation", app)
        self.assertIn("paymentApprovalConfirmationPayload", app)
        self.assertIn("approval_fingerprint", app)
        self.assertIn("I reviewed the merchant, amount, recipient, origin, final button text, and after-approval result.", self.html)
        self.assertIn("approval-confirm", self.html)
        self.assertIn('"file_upload"', app)


if __name__ == "__main__":
    unittest.main()
